process INDEX_REFERENCE {
    tag "Indexing Reference"
    label 'process_single'
    
    // Reuse the BWA + Samtools container
    container "quay.io/biocontainers/mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79fd2b40:219b6c272b25e7e642ae3ff0bf0c5c81a5135ab4-0"

    input:
    path ref_fasta

    output:
    // This grabs the .fai, .bwt, .pac, .ann, .amb, .sa files generated by the indexers
    path "${ref_fasta}.*", emit: indexes

    script:
    """
    # 1. Index for Samtools
    samtools faidx ${ref_fasta}
    
    # 2. Index for BWA
    bwa index ${ref_fasta}
    """
}
